config/routes.rb
Rails.application.routes.draw do

  root to: 'entries#index'

  get 'start_entry' => 'entries#start'
  post 'create_running' => 'entries#create_running'

  resources :entries

end

app/models/entry.rb
class Entry < ActiveRecord::Base

  validates :start, presence: true
  validates :notes, presence: true

  def duration
    stop = self.stop ? self.stop : Time.now
    Duration.new(stop - self.start)
  end

  def start_time_formatted
    format_time(self.start)
  end

  def stop_time_formatted
    format_time(self.stop)
  end

  # I don't want to deal with days so I'd rather just handle hours greater than a day with an integer number of hours
  # As a side note, it's pretty cool how he made this formatting work
  # See docs here: http://www.rubydoc.info/github/peleteiro/ruby-duration/master/Duration

  def duration_formatted
    if self.duration.days > 0
      hours = self.duration.total / 60 / 60
      self.duration.format "#{hours}:%M:%S"
    else
      self.duration.format "%H:%M:%S"
    end
  end

  def date_formatted
    format_date(self.start)
  end

  def running?
    # TODO: What would be the difference of using "not" here instead of "!"?
    ! self.stop
  end

  private

  def format_time(time)
    # This line is a little strange--ActiveRecord saves times in a format that defaults to Greenwich Mean Time. to_time fixes this problem
    time ? time.to_time.strftime("%H:%M:%S") : "--"
  end

  def format_date(time)
    month_dict = { 1 => "Jan", 2 => "Feb", 3 => "Mar", 4 => "Apr", 5 => "May", 6 => "Jun", 7 => "Jul", 8 => "Aug", 9 => "Sep", 10 => "Oct", 11 => "Nov", 12 => "Dec" }
    day_dict = { 1 => "Mon", 2 =>"Tue", 3 =>"Wed", 4 =>"Thu", 5 =>"Fri", 6 =>"Sat", 7 => "Sun" }
    day_of_week = day_dict[time.wday]
    month = month_dict[time.month]
    "#{day_of_week} #{month} #{time.day}, #{time.year}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  def index
    @entries = Entry.all
  end

  def show
  end

  def start
    @entry = Entry.new
  end

  def new
    @entry = Entry.new
  end

  def create_running
    running_entry_params = entry_params
    running_entry_params["start"] = Time.now
    @entry = Entry.all.build(running_entry_params)

    if @entry.save
      redirect_to entries_path
    else
      flash[:error] = "There was a problem creating the entry. Please try again."
      render start_entry_path
    end
  end

  def create
    @entry = Entry.all.build(entry_params)
    if @entry.save
      redirect_to entries_path
    else
      flash[:error] = "There was a problem creating the entry. Please try again."
      render :index
    end
  end

  def edit
  end

  def update
    @entry.update_attributes(entry_params)

    if @entry.save
      redirect_to entries_path
    else
      flash[:error] = "There was a problem updating the entry. Please try again."
      render :edit
    end
  end

  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_path, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def set_entry
    @entry = Entry.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def entry_params
    params.require(:entry).permit(:start, :stop, :notes)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_form.html.erb
<%= bootstrap_form_for entry = Entry.new(:start => Time.now) do |f| %>
  <tr>

    <td class="text-center">
      <%= f.date_select :start, class: 'form-control', use_short_month: true, order: [:month, :day, :year], hide_label: true, placeholder: entry.date_formatted %>
    </td>

    <td class="text-center">
      <%= f.time_select :start, ignore_date: true, default: {:hour => 10, :minute => 30}, hide_label: true, class: 'form-control' %>
    </td>

    <td class="text-center">
      <%= f.time_select :stop, class: 'form-control', hide_label: true, placeholder: "hh:mm" %>
    </td>

    <td></td>

    <td class="text-center">
      <%= f.text_field :notes, class: 'form-control notes-field', hide_label: true, placeholder: "Description of the activity" %>
    </td>

    <td class="text-center">
      <%= f.submit "begin", name: 'begin', value: 'begin', class: 'btn btn-xs btn-success' %>
      <%= f.submit "finish", name: 'finish', value: 'finish', class: 'btn btn-xs btn-danger' %>
    </td>

  </tr>
<% end %>

app/views/entries/edit.html.erb
<div class="container">
  <h2>Editing Entry</h2>

  <% if @entry.errors.any?  %>
    <div class="alert alert-danger">
      <h4>There <%= @entry.errors.count > 1 ? "are " : "is " %><%= pluralize(@entry.errors.count, "error") %></h4>
      <ul>
        <% @entry.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_for @entry do |f| %>
    <div class="form-group">
      <%#<%= f.label :date %>%>
      <%#<%= f.date_field_tag :date, class: 'form-control', placeholder: "mm/dd/yyyy" %>%>
    </div>

    <div class="form-group">
      <%= f.label :start %>
      <%= f.time_field :start, class: 'form-control', placeholder: "hh:mm" %>
    </div>

    <div class="form-group">
      <%= f.label :stop %>
      <%= f.time_field :stop, class: 'form-control', placeholder: "hh:mm" %>
    </div>

    <div class="form-group">
      <%= f.label :notes %>
      <%= f.text_area :notes, class: 'form-control', placeholder: "Description of the activity" %>
    </div>

    <%= f.submit "Save", class: 'btn btn-success' %>

  <% end %>

</div>

app/views/entries/index.html.erb
<div class="container">
  <h1>Time Entries</h1>

  <table class="table table-striped">
    <tr>
      <th class="text-center">Day</th>
      <th class="text-center">Start</th>
      <th class="text-center">End</th>
      <th class="text-center">Duration</th>
      <th class="text-center">Note</th>
    </tr>

    <% @entries.each do |entry| %>
      <tr>
        <td class="text-center">
          <%= entry.date_formatted %>
        </td>

        <td class="text-center">
          <%= entry.start_time_formatted %>
        </td>

        <td class="text-center">
          <%= entry.stop_time_formatted %>
        </td>

        <td class="text-center">
          <%= entry.duration_formatted %>
        </td>

        <td class="text-center">
          <%= entry.notes %>
        </td>
        <td>
          <%= link_to "edit", edit_entry_path(entry) %>
          <%= link_to "delete", entry_path(entry), method: :delete %>

        </td>
      </tr>
    <% end %>
    <tr>
      <%= render partial: 'entries/form' %>
    </tr>
  </table>

  <%= link_to "New Entry", new_entry_path, class: "btn btn-success" %>
  <%= link_to "Start", start_entry_path, class: "btn btn-primary" %>

</div>

app/views/entries/new.html.erb
<div class="container">
  <h2>New Entry</h2>

  <% if @entry.errors.any?  %>
    <div class="alert alert-danger">
      <h4>There <%= @entry.errors.count > 1 ? "are " : "is " %><%= pluralize(@entry.errors.count, "error") %></h4>
      <ul>
        <% @entry.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_for @entry do |f| %>
    <div class="form-group">
      <%#<%= f.label :date %>%>
      <%#<%= f.date_field_tag :date, class: 'form-control', placeholder: "mm/dd/yyyy" %>%>
    </div>

    <div class="form-group">
      <%= f.label :start %>
      <%= f.time_field :start, class: 'form-control', placeholder: "hh:mm" %>
    </div>

    <div class="form-group">
      <%= f.label :stop %>
      <%= f.time_field :stop, class: 'form-control', placeholder: "hh:mm" %>
    </div>

    <div class="form-group">
      <%= f.label :notes %>
      <%= f.text_area :notes, class: 'form-control', placeholder: "Description of the activity" %>
    </div>

    <%= f.submit "Save", class: 'btn btn-success' %>

  <% end %>

</div>

app/views/entries/show.html.erb
<%= @entry.id %>

app/views/entries/start.html.erb
<div class="container">
  <h2>Starting Entry</h2>

  <% if @entry.errors.any?  %>
    <div class="alert alert-danger">
      <h4>There <%= @entry.errors.count > 1 ? "are " : "is " %><%= pluralize(@entry.errors.count, "error") %></h4>
      <ul>
        <% @entry.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_for @entry, :url => url_for(:action => 'create_running') do |f| %>

    <div class="form-group">
      <%= f.label :notes %>
      <%= f.text_area :notes, class: 'form-control', placeholder: "Description of the activity" %>
    </div>

    <%= f.submit "Save", class: 'btn btn-success' %>

  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Timewatch</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="bootstrap-editable/css/bootstrap-editable.css" rel="stylesheet">
  <script src="bootstrap-editable/js/bootstrap-editable.js"></script>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Hello world!</h1>